# -*- coding: utf-8 -*-
"""weld_complete_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y8Q6V7T8NIPGE7lF0gz06bHAHIGuMfo6

## Step 1 — Install & Setup
"""

!pip install -q kaggle

import numpy as np
import os, json, cv2, gc, zipfile, shutil
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Dropout, GlobalAveragePooling2D
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    classification_report, confusion_matrix,
    roc_curve, auc, precision_recall_curve,
    average_precision_score, precision_recall_fscore_support
)
from sklearn.preprocessing import label_binarize
from sklearn.manifold import TSNE
from tqdm.notebook import tqdm
from collections import Counter

# GPU setup
gpus = tf.config.list_physical_devices('GPU')
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)
print('TensorFlow :', tf.__version__)
print('GPU        :', gpus if gpus else 'NOT FOUND — go to Runtime > Change runtime type > T4 GPU')

# Constants
IMG_SIZE          = (224, 224)
SAMPLES_PER_CLASS = 500
NUM_CLASSES       = 6
BATCH_SIZE        = 32
LABEL_NAMES       = ['Good weld', 'Burn through', 'Contamination',
                      'Lack of fusion', 'Misalignment', 'Lack of penetration']
COLORS            = ['#2a78d6','#e34948','#2eab6e','#f0a500','#9b59b6','#e67e22']
TRAIN_DIR         = '/content/al5083/train/'
TEST_DIR          = '/content/al5083/test/'
CKPT_PATH         = '/content/mobilenetv2_weld_best.h5'
SAVE_DIR          = '/content/all_results/'
os.makedirs(SAVE_DIR, exist_ok=True)
print('Setup complete.')

"""## Step 2 — Kaggle Auth & Download"""

# ── I will paste my Kaggle token here ─────────────────────────────────────────────
KAGGLE_TOKEN = 'KGAT_your_token_here'   # <-- replace with KGAT_... token
# ─────────────────────────────────────────────────────────────────────────────

os.environ['KAGGLE_API_TOKEN'] = KAGGLE_TOKEN
os.makedirs(os.path.expanduser('~/.kaggle'), exist_ok=True)
with open(os.path.expanduser('~/.kaggle/access_token'), 'w') as f:
    f.write(KAGGLE_TOKEN)
os.chmod(os.path.expanduser('~/.kaggle/access_token'), 0o600)

print('Downloading dataset...')
!kaggle datasets download -d danielbacioiu/tig-aluminium-5083 -p /content/

print('Extracting...')
with zipfile.ZipFile('/content/tig-aluminium-5083.zip', 'r') as zf:
    zf.extractall('/content/')
os.remove('/content/tig-aluminium-5083.zip')
print('Done! Dataset ready.')
!ls /content/al5083/

"""## Step 3 — Load & Preprocess Images"""

def preprocess_image(path):
    img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
    if img is None:
        return None
    img = cv2.resize(img, IMG_SIZE)
    img = np.stack((img,) * 3, axis=-1)   # grayscale -> 3-channel
    return img

def load_dataset(base_dir, json_file, samples_per_class=None, desc='Loading'):
    with open(json_file) as f:
        label_map = json.load(f)
    keys = list(label_map.keys())
    np.random.shuffle(keys)
    class_counts = [0] * NUM_CLASSES
    images, labels = [], []
    for key in tqdm(keys, desc=desc):
        label = label_map[key]
        if samples_per_class and class_counts[label] >= samples_per_class:
            continue
        path = os.path.join(base_dir, key)
        if not os.path.exists(path):
            continue
        img = preprocess_image(path)
        if img is None:
            continue
        images.append(img)
        labels.append(label)
        class_counts[label] += 1
    print(f'  {len(images)} images | counts: {class_counts}')
    return np.array(images, dtype=np.uint8), np.array(labels, dtype=np.int32)

np.random.seed(42)
print('Loading training images...')
X_all, y_all = load_dataset(TRAIN_DIR, TRAIN_DIR + 'train.json',
                             SAMPLES_PER_CLASS, 'Train')
print('Loading test images...')
X_test, y_test = load_dataset(TEST_DIR, TEST_DIR + 'test.json',
                               None, 'Test')
print(f'Train array : {X_all.shape}  ({X_all.nbytes/1e6:.0f} MB)')
print(f'Test  array : {X_test.shape}  ({X_test.nbytes/1e6:.0f} MB)')

"""## Step 4 — Dataset Visualisation"""

# Class distribution
_, counts = np.unique(y_all, return_counts=True)
fig, ax = plt.subplots(figsize=(10, 4))
ax.bar(LABEL_NAMES, counts, color='#2a78d6', edgecolor='white')
ax.set_title('Training Set Class Distribution', fontsize=13)
ax.set_ylabel('Number of images')
plt.xticks(rotation=20, ha='right')
for i, c in enumerate(counts):
    ax.text(i, c + 2, str(c), ha='center', fontsize=10, fontweight='bold')
plt.tight_layout()
plt.savefig(SAVE_DIR + 'class_distribution.png', dpi=150, bbox_inches='tight')
plt.show()

# One sample per class
fig, axes = plt.subplots(2, 3, figsize=(14, 8))
for cls in range(NUM_CLASSES):
    idx = np.where(y_all == cls)[0][0]
    r, c = divmod(cls, 3)
    axes[r, c].imshow(X_all[idx])
    axes[r, c].set_title(f'Class {cls}: {LABEL_NAMES[cls]}', fontsize=10)
    axes[r, c].axis('off')
plt.suptitle('One Sample Per Defect Class', fontsize=14)
plt.tight_layout()
plt.savefig(SAVE_DIR + 'sample_per_class.png', dpi=150, bbox_inches='tight')
plt.show()
print('Saved class_distribution.png and sample_per_class.png')

"""## Step 5 — Train/Validation Split"""

X_train, X_val, y_train, y_val = train_test_split(
    X_all, y_all, test_size=0.20, random_state=42, stratify=y_all
)
del X_all, y_all   # free RAM — no longer needed
gc.collect()
print(f'Train : {X_train.shape[0]} images')
print(f'Val   : {X_val.shape[0]} images')
print(f'Test  : {X_test.shape[0]} images')
print('RAM freed.')

"""## Step 6 — Data Generators with Augmentation"""

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=15,
    width_shift_range=0.10,
    height_shift_range=0.10,
    horizontal_flip=True,
    brightness_range=[0.85, 1.15],
    zoom_range=0.10,
    fill_mode='nearest'
)
eval_datagen = ImageDataGenerator(rescale=1./255)

train_gen = train_datagen.flow(X_train, y_train, batch_size=BATCH_SIZE, shuffle=True,  seed=42)
val_gen   = eval_datagen.flow(X_val,   y_val,   batch_size=BATCH_SIZE, shuffle=False)
test_gen  = eval_datagen.flow(X_test,  y_test,  batch_size=BATCH_SIZE, shuffle=False)

# Visualise augmented samples
aug_imgs, aug_lbls = next(train_gen)
fig, axes = plt.subplots(2, 5, figsize=(16, 7))
for i, ax in enumerate(axes.flatten()):
    ax.imshow(aug_imgs[i]); ax.set_title(LABEL_NAMES[int(aug_lbls[i])], fontsize=8); ax.axis('off')
plt.suptitle('Augmented Training Samples', fontsize=13)
plt.tight_layout()
plt.savefig(SAVE_DIR + 'augmented_samples.png', dpi=150, bbox_inches='tight')
plt.show()
print(f'Generators ready. Train batches: {len(train_gen)}')

"""## Step 7 — Build MobileNetV2 Model"""

base_model = MobileNetV2(weights='imagenet', include_top=False,
                          input_shape=(224, 224, 3), alpha=1.0)
for layer in base_model.layers:
    layer.trainable = False
for layer in base_model.layers[-20:]:
    layer.trainable = True

x = base_model.output
x = GlobalAveragePooling2D(name='gap')(x)
x = Dense(256, activation='relu', name='dense_256')(x)
x = Dropout(0.50)(x)
x = Dense(128, activation='relu', name='dense_128')(x)
x = Dropout(0.30)(x)
x = Dense(NUM_CLASSES, activation='softmax', name='output')(x)

model = Model(inputs=base_model.input, outputs=x)
model.compile(
    optimizer=Adam(learning_rate=1e-4),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

trainable = sum(np.prod(w.shape) for w in model.trainable_weights)
total     = model.count_params()
print(f'Total params     : {total:,}')
print(f'Trainable params : {trainable:,}')
print(f'Frozen params    : {total - trainable:,}')

# Find last spatial conv layer for Grad-CAM (auto-detected)
GRADCAM_LAYER = None
for layer in reversed(model.layers):
    if hasattr(layer, 'output') and len(layer.output.shape) == 4:
        GRADCAM_LAYER = layer.name
        break
print(f'Grad-CAM layer   : {GRADCAM_LAYER}')

"""## Step 8 — Train"""

callbacks = [
    ModelCheckpoint(CKPT_PATH, monitor='val_accuracy', save_best_only=True,
                    mode='max', verbose=1),
    EarlyStopping(monitor='val_accuracy', patience=10, mode='max',
                  restore_best_weights=True, verbose=1),
    ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=4,
                      min_lr=1e-7, verbose=1)
]

print('Training started...')
history = model.fit(
    train_gen, epochs=50,
    validation_data=val_gen,
    callbacks=callbacks,
    verbose=1
)
best_val_acc = max(history.history['val_accuracy'])
print(f'\nBest validation accuracy : {best_val_acc*100:.2f}%')

"""---
# ── RESULTS ─────────────────────────────────────────────────────────────────

## Result 1 — Training Curves
"""

epochs_ran = range(1, len(history.history['accuracy']) + 1)
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].plot(epochs_ran, history.history['accuracy'],     lw=2, color='#2a78d6', label='Train')
axes[0].plot(epochs_ran, history.history['val_accuracy'], lw=2, color='#e34948', ls='--', label='Validation')
axes[0].set_title('Accuracy vs Epoch', fontsize=13); axes[0].set_xlabel('Epoch')
axes[0].set_ylabel('Accuracy'); axes[0].legend(); axes[0].grid(True, alpha=0.3)
axes[0].set_ylim([0, 1.05])

axes[1].plot(epochs_ran, history.history['loss'],     lw=2, color='#2a78d6', label='Train')
axes[1].plot(epochs_ran, history.history['val_loss'], lw=2, color='#e34948', ls='--', label='Validation')
axes[1].set_title('Loss vs Epoch', fontsize=13); axes[1].set_xlabel('Epoch')
axes[1].set_ylabel('Loss'); axes[1].legend(); axes[1].grid(True, alpha=0.3)

plt.suptitle('MobileNetV2 Training History — Weld Defect Detection', fontsize=14)
plt.tight_layout()
plt.savefig(SAVE_DIR + 'training_curves.png', dpi=150, bbox_inches='tight')
plt.show()
print('Saved training_curves.png')

"""## Result 2 — Test Evaluation & Predictions"""

model.load_weights(CKPT_PATH)
test_loss, test_acc = model.evaluate(test_gen, verbose=1)
print(f'\nTest Loss     : {test_loss:.4f}')
print(f'Test Accuracy : {test_acc*100:.2f}%')

y_pred_probs = model.predict(test_gen, verbose=1)
y_pred = np.argmax(y_pred_probs, axis=1)
y_true = y_test[:len(y_pred)]   # align lengths
print(f'Predictions: {len(y_pred)} samples')

"""## Result 3 — Confusion Matrix"""

cm      = confusion_matrix(y_true, y_pred)
cm_norm = cm.astype('float') / cm.sum(axis=1, keepdims=True)

fig, axes = plt.subplots(1, 2, figsize=(20, 7))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=LABEL_NAMES,
            yticklabels=LABEL_NAMES, ax=axes[0], linewidths=0.5, linecolor='white')
axes[0].set_title('Confusion Matrix (counts)', fontsize=13)
axes[0].set_xlabel('Predicted'); axes[0].set_ylabel('True')
axes[0].tick_params(axis='x', rotation=25)

sns.heatmap(cm_norm, annot=True, fmt='.2f', cmap='Blues', xticklabels=LABEL_NAMES,
            yticklabels=LABEL_NAMES, ax=axes[1], linewidths=0.5, linecolor='white',
            vmin=0, vmax=1)
axes[1].set_title('Confusion Matrix (row-normalised)', fontsize=13)
axes[1].set_xlabel('Predicted'); axes[1].set_ylabel('True')
axes[1].tick_params(axis='x', rotation=25)

plt.suptitle('Test Set Confusion Matrix — MobileNetV2 Weld Defect Detection', fontsize=14)
plt.tight_layout()
plt.savefig(SAVE_DIR + 'confusion_matrix.png', dpi=150, bbox_inches='tight')
plt.show()
print('Saved confusion_matrix.png')

"""## Result 4 — Per-class Accuracy"""

per_class_acc = cm_norm.diagonal()
colors_bar    = ['#2a78d6' if a >= 0.80 else '#eda100' if a >= 0.60 else '#e34948'
                 for a in per_class_acc]

fig, ax = plt.subplots(figsize=(11, 5))
bars = ax.bar(LABEL_NAMES, per_class_acc * 100, color=colors_bar, edgecolor='white', lw=0.8)
ax.axhline(80, color='gray', ls='--', lw=1.2, label='80% threshold')
ax.set_title('Per-class Test Accuracy — MobileNetV2', fontsize=13)
ax.set_xlabel('Defect class'); ax.set_ylabel('Accuracy (%)')
ax.set_ylim([0, 115]); ax.legend(); plt.xticks(rotation=20, ha='right')
for bar, acc in zip(bars, per_class_acc):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 1.5,
            f'{acc*100:.1f}%', ha='center', va='bottom', fontsize=10, fontweight='bold')
plt.tight_layout()
plt.savefig(SAVE_DIR + 'per_class_accuracy.png', dpi=150, bbox_inches='tight')
plt.show()
print('Saved per_class_accuracy.png')

"""## Result 5 — Sample Predictions"""

np.random.seed(0)
indices = np.random.choice(len(y_true), size=10, replace=False)
fig, axes = plt.subplots(2, 5, figsize=(18, 8))
for ax, idx in zip(axes.flatten(), indices):
    ax.imshow(X_test[idx])
    pred, truth = y_pred[idx], y_true[idx]
    color = '#1baf7a' if pred == truth else '#e34948'
    for spine in ax.spines.values():
        spine.set_edgecolor(color); spine.set_linewidth(4)
    ax.set_title(f'Pred: {LABEL_NAMES[pred]}\nTrue: {LABEL_NAMES[truth]}',
                 fontsize=8, color=color)
    ax.axis('off')
plt.suptitle('Sample Predictions  (green = correct | red = incorrect)', fontsize=13)
plt.tight_layout()
plt.savefig(SAVE_DIR + 'sample_predictions.png', dpi=150, bbox_inches='tight')
plt.show()
print('Saved sample_predictions.png')

"""## Result 6 — Classification Report"""

report = classification_report(y_true, y_pred, target_names=LABEL_NAMES, digits=4)
print('Classification Report\n' + '='*72)
print(report)
with open(SAVE_DIR + 'classification_report.txt', 'w') as f:
    f.write('Classification Report — MobileNetV2 Weld Defect Detection\n')
    f.write('='*72 + '\n' + report)
    f.write(f'\nTest Loss     : {test_loss:.4f}\nTest Accuracy : {test_acc*100:.2f}%\n')
print('Saved classification_report.txt')

"""---
# ── ADDITIONAL ANALYSIS ──────────────────────────────────────────────────────

## Analysis 1 — ROC Curves
"""

y_true_bin = label_binarize(y_true, classes=list(range(NUM_CLASSES)))
auc_scores = []

fig, axes = plt.subplots(2, 3, figsize=(16, 10))
for i, ax in enumerate(axes.flatten()):
    fpr, tpr, _ = roc_curve(y_true_bin[:, i], y_pred_probs[:len(y_true), i])
    roc_auc     = auc(fpr, tpr)
    auc_scores.append(roc_auc)
    ax.plot(fpr, tpr, color=COLORS[i], lw=2.5, label=f'AUC = {roc_auc:.4f}')
    ax.plot([0,1],[0,1], 'k--', lw=1, alpha=0.5, label='Random')
    ax.fill_between(fpr, tpr, alpha=0.08, color=COLORS[i])
    ax.set_title(LABEL_NAMES[i], fontsize=12, fontweight='bold')
    ax.set_xlabel('False Positive Rate'); ax.set_ylabel('True Positive Rate')
    ax.legend(loc='lower right'); ax.grid(True, alpha=0.3)
    ax.set_xlim([0,1]); ax.set_ylim([0,1.05])

plt.suptitle('ROC Curves — One-vs-Rest per Defect Class', fontsize=14)
plt.tight_layout()
plt.savefig(SAVE_DIR + 'roc_curves.png', dpi=150, bbox_inches='tight')
plt.show()
print('AUC Scores:')
for name, score in zip(LABEL_NAMES, auc_scores):
    print(f'  {name:<25}: {score:.4f}')
print(f'  Mean AUC: {np.mean(auc_scores):.4f}')
print('Saved roc_curves.png')

"""## Analysis 2 — Precision-Recall Curves"""

ap_scores = []
fig, axes = plt.subplots(2, 3, figsize=(16, 10))
for i, ax in enumerate(axes.flatten()):
    precision, recall, _ = precision_recall_curve(
        y_true_bin[:, i], y_pred_probs[:len(y_true), i])
    ap       = average_precision_score(y_true_bin[:, i], y_pred_probs[:len(y_true), i])
    ap_scores.append(ap)
    baseline = np.sum(y_true == i) / len(y_true)
    ax.plot(recall, precision, color=COLORS[i], lw=2.5, label=f'AP = {ap:.4f}')
    ax.axhline(baseline, color='gray', ls='--', lw=1, label=f'Baseline = {baseline:.2f}')
    ax.fill_between(recall, precision, alpha=0.08, color=COLORS[i])
    ax.set_title(LABEL_NAMES[i], fontsize=12, fontweight='bold')
    ax.set_xlabel('Recall'); ax.set_ylabel('Precision')
    ax.legend(loc='upper right'); ax.grid(True, alpha=0.3)
    ax.set_xlim([0,1]); ax.set_ylim([0,1.05])

plt.suptitle('Precision-Recall Curves — MobileNetV2 Weld Defect Detection', fontsize=14)
plt.tight_layout()
plt.savefig(SAVE_DIR + 'precision_recall_curves.png', dpi=150, bbox_inches='tight')
plt.show()
print(f'Mean Average Precision (mAP): {np.mean(ap_scores):.4f}')
print('Saved precision_recall_curves.png')

"""## Analysis 3 — Grad-CAM Heatmaps"""

def make_gradcam_heatmap(img_array, model, conv_layer_name, pred_index):
    grad_model = Model(
        inputs  = model.inputs,
        outputs = [model.get_layer(conv_layer_name).output, model.output]
    )
    with tf.GradientTape() as tape:
        conv_out, preds = grad_model(img_array)
        class_score     = preds[:, pred_index]
    grads        = tape.gradient(class_score, conv_out)
    pooled_grads = tf.reduce_mean(grads, axis=(0, 1, 2))
    heatmap      = conv_out[0] @ pooled_grads[..., tf.newaxis]
    heatmap      = tf.squeeze(heatmap)
    heatmap      = tf.maximum(heatmap, 0)
    max_val      = tf.math.reduce_max(heatmap)
    if max_val > 0:
        heatmap = heatmap / max_val
    return heatmap.numpy()

def overlay_gradcam(img_uint8, heatmap, alpha=0.4):
    h = cv2.resize(heatmap, (img_uint8.shape[1], img_uint8.shape[0]))
    h = np.uint8(255 * h)
    h = cv2.applyColorMap(h, cv2.COLORMAP_JET)
    h = cv2.cvtColor(h, cv2.COLOR_BGR2RGB)
    return cv2.addWeighted(img_uint8, 1 - alpha, h, alpha, 0)

fig, axes = plt.subplots(6, 3, figsize=(12, 24))
for cls in range(NUM_CLASSES):

    correct_idx = np.where((y_true == cls) & (y_pred == cls))[0]
    idx         = correct_idx[0] if len(correct_idx) > 0 else np.where(y_true == cls)[0][0]

    img_uint8 = X_test[idx]
    img_input = np.expand_dims(img_uint8.astype('float32') / 255.0, axis=0)

    heatmap = make_gradcam_heatmap(img_input, model, GRADCAM_LAYER, cls)
    overlay = overlay_gradcam(img_uint8, heatmap)

    axes[cls, 0].imshow(img_uint8)
    axes[cls, 0].set_ylabel(LABEL_NAMES[cls], fontsize=9, fontweight='bold')
    axes[cls, 0].axis('off')
    axes[cls, 1].imshow(heatmap, cmap='jet')
    axes[cls, 1].axis('off')
    axes[cls, 2].imshow(overlay)
    axes[cls, 2].axis('off')

for col, title in enumerate(['Original', 'Grad-CAM Heatmap', 'Overlay']):
    axes[0, col].set_title(title, fontsize=12, fontweight='bold', pad=10)

plt.suptitle('Grad-CAM: Regions the Model Focuses on Per Defect Class', fontsize=14, y=1.01)
plt.tight_layout()
plt.savefig(SAVE_DIR + 'gradcam_per_class.png', dpi=150, bbox_inches='tight')
plt.show()
print('Saved gradcam_per_class.png')

"""## Analysis 4 — Misclassification Analysis"""

wrong_mask = y_pred != y_true
wrong_idx  = np.where(wrong_mask)[0]
wrong_true = y_true[wrong_mask]
wrong_pred = y_pred[wrong_mask]

top_confusions = Counter(zip(wrong_true.tolist(), wrong_pred.tolist())).most_common(6)
print(f'Total wrong: {len(wrong_idx)} / {len(y_true)} ({len(wrong_idx)/len(y_true)*100:.1f}%)')
print('\nTop confused pairs (True → Predicted):')
for (tc, pc), count in top_confusions:
    print(f'  {LABEL_NAMES[tc]:<25} → {LABEL_NAMES[pc]:<25}: {count}')

fig, axes = plt.subplots(2, 3, figsize=(16, 10))
for ax, ((tc, pc), count) in zip(axes.flatten(), top_confusions):
    mask = (wrong_true == tc) & (wrong_pred == pc)
    pair_idx = wrong_idx[mask]
    if len(pair_idx) == 0:
        ax.axis('off'); continue
    img  = X_test[pair_idx[0]]
    conf = y_pred_probs[pair_idx[0], pc] * 100
    ax.imshow(img)
    ax.set_title(f'True: {LABEL_NAMES[tc]}\nPred: {LABEL_NAMES[pc]}\n'
                 f'Confidence: {conf:.1f}%  |  {count} occurrences',
                 fontsize=9, color='#c0392b')
    for spine in ax.spines.values():
        spine.set_edgecolor('#e34948'); spine.set_linewidth(3)
    ax.axis('off')

plt.suptitle('Most Common Misclassifications', fontsize=14)
plt.tight_layout()
plt.savefig(SAVE_DIR + 'misclassification_analysis.png', dpi=150, bbox_inches='tight')
plt.show()
print('Saved misclassification_analysis.png')

"""## Analysis 5 — t-SNE Feature Embedding"""

# Extracted features from GAP layer
feature_model = Model(inputs=model.input, outputs=model.get_layer('gap').output)

# Using max 1200 samples for speed
MAX_N = 1200
if len(X_test) > MAX_N:
    sub_idx  = np.random.choice(len(X_test), MAX_N, replace=False)
    X_sub    = X_test[sub_idx].astype('float32') / 255.0
    y_sub    = y_true[sub_idx]
else:
    X_sub = X_test.astype('float32') / 255.0
    y_sub = y_true

print(f'Extracting features from {len(X_sub)} images...')
features = feature_model.predict(X_sub, batch_size=BATCH_SIZE, verbose=1)
print(f'Feature shape: {features.shape}')

print('Running t-SNE (~2 minutes)...')
tsne_2d = TSNE(n_components=2, perplexity=30, random_state=42,
               n_iter=1000, verbose=0).fit_transform(features)

fig, ax = plt.subplots(figsize=(12, 9))
for cls in range(NUM_CLASSES):
    mask = y_sub == cls
    ax.scatter(tsne_2d[mask, 0], tsne_2d[mask, 1],
               c=COLORS[cls], label=LABEL_NAMES[cls],
               alpha=0.65, s=18, edgecolors='none')
ax.set_title('t-SNE Feature Embedding\nHow MobileNetV2 internally separates defect classes',
             fontsize=12)
ax.set_xlabel('t-SNE Dimension 1'); ax.set_ylabel('t-SNE Dimension 2')
ax.legend(markerscale=2, fontsize=10, framealpha=0.9)
ax.grid(True, alpha=0.2)
plt.tight_layout()
plt.savefig(SAVE_DIR + 'tsne_embedding.png', dpi=150, bbox_inches='tight')
plt.show()
print('Saved tsne_embedding.png')

"""## Analysis 6 — Confidence Distribution"""

fig, axes = plt.subplots(2, 3, figsize=(16, 9))
for cls, ax in enumerate(axes.flatten()):
    mask    = y_true == cls
    conf    = y_pred_probs[mask, cls]
    correct = y_pred[mask] == cls
    ax.hist(conf[correct],  bins=20, alpha=0.7, color='#2eab6e',
            label=f'Correct ({correct.sum()})',  density=True)
    ax.hist(conf[~correct], bins=20, alpha=0.7, color='#e34948',
            label=f'Wrong ({(~correct).sum()})', density=True)
    ax.axvline(0.5, color='gray', ls='--', lw=1)
    ax.set_title(LABEL_NAMES[cls], fontsize=11, fontweight='bold')
    ax.set_xlabel('Model Confidence'); ax.set_ylabel('Density')
    ax.legend(fontsize=9); ax.set_xlim([0,1]); ax.grid(True, alpha=0.3)

plt.suptitle('Confidence Distribution — Correct vs Incorrect Predictions', fontsize=13)
plt.tight_layout()
plt.savefig(SAVE_DIR + 'confidence_distribution.png', dpi=150, bbox_inches='tight')
plt.show()
print('Saved confidence_distribution.png')

"""## Analysis 7 — Full Metrics Summary"""

prec, rec, f1, sup = precision_recall_fscore_support(y_true, y_pred)

header = f'{"Class":<25} {"Precision":>10} {"Recall":>10} {"F1":>10} {"AUC":>10} {"AP":>10} {"Support":>8}'
sep    = '='*83
rows   = [f'{LABEL_NAMES[i]:<25} {prec[i]:>10.4f} {rec[i]:>10.4f} {f1[i]:>10.4f} '
          f'{auc_scores[i]:>10.4f} {ap_scores[i]:>10.4f} {sup[i]:>8}'
          for i in range(NUM_CLASSES)]
macro  = (f'{"Macro Average":<25} {np.mean(prec):>10.4f} {np.mean(rec):>10.4f} '
          f'{np.mean(f1):>10.4f} {np.mean(auc_scores):>10.4f} {np.mean(ap_scores):>10.4f}')

full_report = '\n'.join([sep, header, sep] + rows + [sep, macro, sep])
print(full_report)

with open(SAVE_DIR + 'full_metrics_summary.txt', 'w') as f:
    f.write('Full Metrics — MobileNetV2 Weld Defect Detection\n')
    f.write(f'Test Accuracy : {test_acc*100:.2f}%  |  Test Loss: {test_loss:.4f}\n\n')
    f.write(full_report)
print('Saved full_metrics_summary.txt')

"""---
## Final Summary & Download
"""

shutil.copy(CKPT_PATH, SAVE_DIR)
shutil.make_archive('/content/all_results', 'zip', SAVE_DIR)

print('='*55)
print('         FINAL RESULTS SUMMARY')
print('='*55)
print(f'  Model          : MobileNetV2')
print(f'  Train samples  : {X_train.shape[0]}')
print(f'  Val   samples  : {X_val.shape[0]}')
print(f'  Test  samples  : {len(y_true)}')
print(f'  Best val acc   : {best_val_acc*100:.2f}%')
print(f'  Test Accuracy  : {test_acc*100:.2f}%')
print(f'  Test Loss      : {test_loss:.4f}')
print(f'  Mean AUC       : {np.mean(auc_scores):.4f}')
print(f'  Mean AP (mAP)  : {np.mean(ap_scores):.4f}')
print('='*55)
print('\nFiles saved:')
for f in sorted(os.listdir(SAVE_DIR)):
    print(f'  {f}')

from google.colab import files
files.download('/content/all_results.zip')
print('\nDownloading all_results.zip...')